### ISSUE TITLE
Just a workaround

### ISSUE THREAD

**Issue by julyusito** [gewuerzgurke84/pfSense-blockerNG2named#1]
Hello,

Thanks by the script, I try it yesterday and found an issue when execute the script. If the whitelist file does not exist or even is empty, no zone file is created.  I figured out a workaround, creating the file manually and add at least one register for my domain.

This is my pfsense version:
Version | 2.4.5-RELEASE-p1 (amd64) built on Tue Jun 02 17:51:17 EDT 2020 FreeBSD 11.3-STABLE

Thanks.

**Comment by gewuerzgurke84** [comment]
Hi,
thanks for your request and sorry for the late reply, I'll add a check for that.
Best Regards,
 Alex

**Comment by gewuerzgurke84** [comment]
Fixed with https://github.com/gewuerzgurke84/pfSense-blockerNG2named/commit/4230fc1d4ce951e48b289ceae115599e97b25342
