### ISSUE TITLE
Reload bind instead of restart

### ISSUE THREAD

**Issue by sjthespian** [gewuerzgurke84/pfSense-blockerNG2named#3]
I made a minor tweak to the code to reload the blacklist zone rather than restarting all of bind. This should make for fewer DNS outages when the list is updated.

Here's a patch (I can do a fork and pull-request if you prefer):
```
diff -ub createBlockingRPZone.sh createBlockingRPZone.sh-installed
--- createBlockingRPZone.sh	2020-12-23 19:19:43.000000000 -0800
+++ createBlockingRPZone.sh-installed	2020-12-23 22:00:08.000000000 -0800
@@ -32,6 +32,9 @@
 # Restart named (Y/N)
 #
 restartNamed="N"
+reloadNamed="Y"
+# if reload is "Y", space-separated list of zones to reload. Ex. "Internal/blackhole"
+reloadZones="Internal/blackhole"

 #
 # Write zone file
@@ -104,5 +107,14 @@
     echo "# Restarting named"
     service named.sh restart
 fi
+if [ "$reloadNamed" == "Y" ]; then
+    echo -n "# Reloading named: "
+    for z in $reloadZones; do
+        echo -n "$z "
+        zcmd=`echo $z | awk -F/ '{printf "%s IN %s\n",$2,$1}'`
+        rndc reload $zcmd
+    done
+    echo
+fi

 echo "# Finished"
```

**Comment by sjthespian** [comment]
FWIW, I have a [fork of your repo](https://github.com/sjthespian/pfSense-blockerNG2named) that includes the above patch as well as some new code that does the following:
- Pulls the whitelist from the pfBlockerNG file instead of requiring a separate file
- Adds support for the top1M list
- Pulls the destVIP from config.xml instead of setting it manually
- Updates the zone serial every time this runs just in case you are sending it to your slaves

**Comment by gewuerzgurke84** [comment]
Hi @sjthespian ,
sorry for the late reply, feel free tosubmit a pull-request. Makes perfectly sense...
Best Regards,
 Alex
